### ISSUE TITLE
Wanna merge ?

### ISSUE THREAD

**Issue by BaQs** [RenierM26/py-ezviz#5]
As I don't have much time maintaining both pypi package & home-assistant module, what do you think of merging our projects together ?

(I know it's not the best way to ask, but couldn't find a way to reach you out)

**Comment by RenierM26** [comment]
Hi BaQs,

Thank you for reaching out! I would love to continue your project. How do you propose we do this?

**Comment by BaQs** [comment]
Good question :)
As you may have seen, it's a first for me. The HA team helped me a lot on making this possible.
How can we work together on the same project ?

**Comment by BaQs** [comment]
Ok I invited you to the repository

**Comment by BaQs** [comment]
We should also merge all of this to the official ezviz ha component :)

**Comment by RenierM26** [comment]
Hi Pierre,

Will do! There are a few fixes I need to make for it to pass the hassio tests. (Also need to rename and test)

Should be done by Saturday (I live in South Africa). Mostly work on this project during weekends.

I have submitted a pull request with my latest pyEzviz changes. I don’t have write access on your “pyEzviz” repository would you mind merging?

Regards.

**Comment by BaQs** [comment]
Hello,

I'm living in France. Hope the COVID "situation" is ok on your side.
I can add you as an owner to the pypi project, just give me your pypi username.

Checking the rights on the repo as well

**Comment by BaQs** [comment]
@RenierM26
RenierM26
Awaiting RenierM26’s response
Pending Invite


Please accept the invite and you'll be able to handle the repo

**Comment by RenierM26** [comment]
Invite accepted. Thank you BaQs!

The PyPi workflow also works perfectly.

**Comment by BaQs** [comment]
BIM !!

honestly, big thanks. Really appreciated :)
#thatsWhyILoveOpenSource
